### PR TITLE
created nl.json

### PR DESCRIPTION
**Pull request by shtjonathan**
Dutch localization file - initial version

### CODE REVIEW

**Comment by moshe-coh** [comment]
please send me the flag of this country, thank you

**Comment by shtjonathan** [comment]
Shalom Moshe,

I just corrected several small typos I found in my initial translation file.

The Dutch flag is like this image below (downloaded from Wikipedia https://nl.wikipedia.org/wiki/Vlag_van_Nederland):


Currently, a lot of upside-down Dutch flags can be seen all over the Netherlands and in some news, mainly used by farmers, fishermen, and many other people, as a sign of distress and call for help...

With many kind greetings and prayers from the Netherlands,
Lehitraot,
samuel

**Comment by shtjonathan** [comment]
Shalom Moshe!

I just realised that perhaps you meant you would be interested in receiving a real, physical flag from the Netherlands; was that what you meant to say?
In that case, please allow me some time to find a flag, and please send me an address where I can send the flag to.

With kind greetings and prayers,
samuel

**Comment by moshe-coh** [comment]
Hi, I meant emoji, but I found it.
Are you Jewish? You can talk on [Telegram](https://t.me/JewsAdmin) 
Thank you.

**Comment by shtjonathan** [comment]
Shalom Moshe,

Ah ok, lmogi… never heard of that, but I’ll look it up!
I’m sorry, I’m just a goy, but my heart is there… I started learning Ivrit together with family and friends from a Jewish Mrs. for around 1,5 years during the time that I was in high school, unfortunately forgot most of it, but now I really wish to study it again…
Thanks for the Telegram link, I’ll check it out!
You’re welcome.

With kind greetings and prayers,
samuel

**Pull request merged**
